### ISSUE TITLE
htpasswd auth error on Fedora 21

### ISSUE THREAD

**Issue by kallisti5** [claudyus/LXC-Web-Panel#54]
Using htpasswd, seen after login
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/lwp-git_-py2.7.egg/lwp/views/auth.py", line 80, in login
    if check_htpasswd(HTPASSWD_FILE, request_username, request_passwd):
  File "/usr/lib/python2.7/site-packages/lwp-git_-py2.7.egg/lwp/utils.py", line 171, in check_htpasswd
    return hmac.compare_digest(crypt.crypt(password, htpasswd), htpasswd)
TypeError: 'NoneType' does not have the buffer interface
```

**Comment by claudyus** [comment]
can you test it again after https://github.com/claudyus/LXC-Web-Panel/commit/242388e373c88be06781777edb5f110cf577a540

**Comment by claudyus** [comment]
please reopen proposed fix doesn't work
