### ISSUE TITLE
/etc/default/lxc-net not found on Debian Jessie

### ISSUE THREAD

**Issue by miguelzabala** [claudyus/LXC-Web-Panel#80]
After install lwp with apt-get and fix some installation problem. When I run manually "/usr/bin/lwp" then go to web page URL and then go to "http://127.0.0.1:5000/settings/lxc-net" got this error:
 
#/usr/bin/lwp
 * Auth type: database
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader
 * Auth type: database
181.47.25.246 - - [14/Apr/2015 16:26:02] "GET /settings/lxc-net HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/share/pyshared/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pyshared/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/pyshared/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/pyshared/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/pyshared/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/lwp/utils.py", line 94, in new_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lwp/views/main.py", line 176, in lxc_net
    return render_template('lxc-net.html', containers=lxc.ls(), cfg=lwp.get_net_settings(), running=lxc.running())
  File "/usr/lib/python2.7/dist-packages/lwp/__init__.py", line 202, in get_net_settings
    raise LxcConfigFileNotComplete('Cannot find lxc-net config file! Check if /etc/default/lxc-net exists')
LxcConfigFileNotComplete: Cannot find lxc-net config file! Check if /etc/default/lxc-net exists

**Comment by claudyus** [comment]
Hi @miguelzabala 

here https://github.com/claudyus/LXC-Web-Panel/issues/74 there is a similar issues and a possible solution. My fault that leave the bug closed also if it is not really clear how @DavidVentura resolve is problem.

Can you better test the proposed scripts and report whats really happens?
